
title: Drew Kristensen
email: dkristensen@pugetsound.edu
description: > # this means to ignore newlines until "baseurl:"
  Student, University of Puget Sound '18
baseurl: "" 
url: "" 
github_username:  dkristensen

sass:
 style: compressed
 
 
# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
