
title: Drew Kristensen
email: drew.kristensen@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Masters Graduate, University of Montreal '21
baseurl: "" 
url: "" 
github_username:  dkristensen

sass:
 style: compressed
 
defaults:
  - scope:
      path: "img/about"
    values:
      about: true

# Tracker
analytics: UA-83979019-1
 
### exclude the instructions / write-up in the README.md
exclude:
- README.md
